// Generated by CoffeeScript 1.8.0
(function() {
  var alert, species, wes, yell;

  species = require('./biology/species');

  yell = function(person) {
    var age_string, class_string, dead_string, gender_string;
    age_string = "" + person.name + " " + (person.dead ? "was" : "is") + " " + person.age + ".";
    gender_string = "" + person.name + "  " + (person.dead ? "was" : "is") + " " + person.gender + ".";
    class_string = "" + person.name + " " + (person.dead ? "was" : "is") + " " + person.class_of_life + "-class.";
    dead_string = "" + person.name + " is " + (person.dead ? "dead" : "alive") + ".";
    return alert("" + age_string + " " + gender_string + " " + class_string + " " + dead_string);
  };

  alert = function(string) {
    return console.log(string);
  };

  wes = new species.Sapiens("Wes", "middle", "Male", 14, false);

  yell(wes);

  wes.grow(3);

  yell(wes);

  alert(wes.species);

}).call(this);
