// Generated by CoffeeScript 1.8.0
(function() {
  var Organism, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Organism = require('./organism').Organism;

  root.Eukaryote = (function(_super) {
    __extends(Eukaryote, _super);

    function Eukaryote(gender, age, dead, species, genus, family, order, the_class, phylum, kingdom) {
      Eukaryote.__super__.constructor.call(this, gender, age, dead, species, genus, family, order, the_class, kingdom, 'Eukaryote');
    }

    return Eukaryote;

  })(Organism);

  root.Archea = (function(_super) {
    __extends(Archea, _super);

    function Archea(gender, age, dead, species, genus, family, order, the_class, phylum, kingdom) {
      Archea.__super__.constructor.call(this, gender, age, dead, species, genus, family, order, the_class, kingdom, 'Archea');
    }

    return Archea;

  })(Organism);

  root.Bacteria = (function(_super) {
    __extends(Bacteria, _super);

    function Bacteria(gender, age, dead, species, genus, family, order, the_class, phylum, kingdom) {
      Bacteria.__super__.constructor.call(this, gender, age, dead, species, genus, family, order, the_class, kingdom, 'Bacteria');
    }

    return Bacteria;

  })(Organism);

}).call(this);
