// Generated by CoffeeScript 1.8.0
(function() {
  var orders, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  orders = require('./orders');

  root.Hominidae = (function(_super) {
    __extends(Hominidae, _super);

    function Hominidae(gender, age, dead, species, genus) {
      Hominidae.__super__.constructor.call(this, gender, age, dead, species, genus, "Hominidae");
    }

    return Hominidae;

  })(orders.Primate);

}).call(this);
