// Generated by CoffeeScript 1.8.0
(function() {
  var families, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  families = require('./families');

  root.Homo = (function(_super) {
    __extends(Homo, _super);

    function Homo(gender, age, dead, species) {
      Homo.__super__.constructor.call(this, gender, age, dead, species, "Homo");
    }

    return Homo;

  })(families.Hominidae);

}).call(this);
