// Generated by CoffeeScript 1.8.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Organism = (function() {
    function Organism(age, dead, species, genus, family, order, _class, phylum, kingdom) {
      this.age = age;
      this.dead = dead;
      this.species = species;
      this.genus = genus;
      this.family = family;
      this.order = order;
      this["class"] = _class;
      this.phylum = phylum;
      this.kingdom = kingdom;
    }

    return Organism;

  })();

  root.Animal = (function(_super) {
    __extends(Animal, _super);

    function Animal(gender, age, dead, species, genus, family, order, the_class, phylum) {
      this.gender = gender;
      Animal.__super__.constructor.call(this, age, dead, species, genus, family, order, the_class, phylum, "Animalia");
    }

    return Animal;

  })(root.Organism);

}).call(this);
