// Generated by CoffeeScript 1.8.0
(function() {
  var classes, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  classes = require('./classes');

  root.Primate = (function(_super) {
    __extends(Primate, _super);

    function Primate(gender, age, dead, species, genus, family) {
      Primate.__super__.constructor.call(this, gender, age, dead, species, genus, family, "Primates");
    }

    return Primate;

  })(classes.Mammal);

}).call(this);
