// Generated by CoffeeScript 1.8.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Organism = (function() {
    function Organism(gender, age, dead, species, genus, family, order, the_class, phylum, kingdom, domain) {
      this.gender = gender;
      this.age = age;
      this.dead = dead;
      this.species = species;
      this.genus = genus;
      this.family = family;
      this.order = order;
      this.the_class = the_class;
      this.phylum = phylum;
      this.kingdom = kingdom;
      this.domain = domain;
    }

    return Organism;

  })();

}).call(this);
