// Generated by CoffeeScript 1.8.0
(function() {
  var kingdoms, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  kingdoms = require('./kingdoms');

  root.Cordata = (function(_super) {
    __extends(Cordata, _super);

    function Cordata(gender, age, dead, species, genus, family, order, the_class) {
      Cordata.__super__.constructor.call(this, gender, age, dead, species, genus, family, order, the_class, "Cordata");
    }

    return Cordata;

  })(kingdoms.Animal);

}).call(this);
