// Generated by CoffeeScript 1.8.0
(function() {
  var genuses, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  genuses = require('./genuses');

  root.Sapiens = (function(_super) {
    __extends(Sapiens, _super);

    function Sapiens(name, class_of_life, gender, age, dead) {
      this.name = name;
      this.class_of_life = class_of_life;
      Sapiens.__super__.constructor.call(this, gender, age, dead, "Sapiens");
    }

    Sapiens.prototype.grow = function(years) {
      this.age += years;
      return console.log("" + this.name + " has grown " + years + " years");
    };

    return Sapiens;

  })(genuses.Homo);

}).call(this);
